version: '2'
services:
    nyan-app:
        image: nyan
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nyan-postgresql:5432/nyan
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nyan-postgresql:
        extends:
            file: postgresql.yml
            service: nyan-postgresql
