version: '2'
services:
    nyan-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/nyan/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=nyan
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
